package com.myteam.my_first_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CreditScore implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int score;

	public CreditScore() {
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public CreditScore(int score) {
		this.score = score;
	}

}