package com.myteam.my_first_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Loan() {
    }




}