package com.myteam.my_planner_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CloudBalancingSolution implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CloudBalancingSolution() {
    }




}