package com.myteam.my_planner_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Computer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int cpu;

	public Computer() {
	}

	public int getCpu() {
		return this.cpu;
	}

	public void setCpu(int cpu) {
		this.cpu = cpu;
	}

	public Computer(int cpu) {
		this.cpu = cpu;
	}

}