package com.myteam.my_planner_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Computer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int cpu;

	private int cost;

	private long id;

	public Computer() {
	}

	public int getCpu() {
		return this.cpu;
	}

	public void setCpu(int cpu) {
		this.cpu = cpu;
	}

	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Computer(int cpu, int cost, long id) {
		this.cpu = cpu;
		this.cost = cost;
		this.id = id;
	}

}