package com.myteam.my_planner_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Process implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int requiredCpu;

	public Process() {
	}

	public int getRequiredCpu() {
		return this.requiredCpu;
	}

	public void setRequiredCpu(int requiredCpu) {
		this.requiredCpu = requiredCpu;
	}

	public Process(int requiredCpu) {
		this.requiredCpu = requiredCpu;
	}

}