package com.myteam.my_planner_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Process implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int requiredCpu;

	@org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"computers"})
	private com.myteam.my_planner_project.Computer computer;

	private long id;

	public Process() {
	}

	public int getRequiredCpu() {
		return this.requiredCpu;
	}

	public void setRequiredCpu(int requiredCpu) {
		this.requiredCpu = requiredCpu;
	}

	public com.myteam.my_planner_project.Computer getComputer() {
		return this.computer;
	}

	public void setComputer(com.myteam.my_planner_project.Computer computer) {
		this.computer = computer;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Process(int requiredCpu,
			com.myteam.my_planner_project.Computer computer, long id) {
		this.requiredCpu = requiredCpu;
		this.computer = computer;
		this.id = id;
	}

}